RasaHQ/rasa_core

rasa_core/processor.py, rasa_core/tracker_store.py, rasa_core/trackers.py, tests/test_policies.py, tests/test_trackers.py, tests/utilities.py
- previously for every loading of a persisted dialogue more `action_listen` events got appended after a restart leading to a messed up feature history - fixed that
=> fixed tracker restart history issues

rasa_core/agent.py
Currently the Agent class can only load instances of itself and not from inherited classes. The `load` function should return `cls(..)` and not `Agent(..)` to enable this.
- Change return of `Agent.load` from `Agent(..)` to `cls(..)`
=> Enable loading of inherited Agent classes

rasa_core/agent.py, rasa_core/events/__init__.py, rasa_core/policies/online_policy_trainer.py, rasa_core/train.py
- allows to use the `train.py` script to start online learning using the `--online` flag
=> Allow to use the train script to start the simple online learning mode on cmd

rasa_core/agent.py, rasa_core/policies/trainer.py
- #54 `remove_duplicates` can be passed to `agent.train`
Is this PR about what you had in mind when formulating #54?
If not maybe you can give me some more insight on how you imagined this change to be :)
If yes I will move on to satisfy further contribution guidelines!
(Off-Topic: Hey Joey, I loved your talk on PyCon.DE!)
=> accepting remove_duplicates as a parameter to agent.train

CHANGELOG.rst, rasa_core/trackers.py, tests/test_trackers.py
- adds a method to the tracker to retrieve the values for an entity from the latest message, e.g. `tracker.get_latest_entity_values("number")` will be `["3"]`
- related to #68
=> Entity retrieval

docs/state.rst
original phrase: 
> by passing ``events`` to the ``log_event`` method
changed to:
> by passing ``events`` to the ``update`` method
- ...
=> change the api name of updating events

docs/interpreters.rst
Fix documentation for Interpreter's return format. **intent** should be a dictionary containing **name** and **confidence**. In the current documentation, the example **intent** provided is a string that will cause `AttributeError: 'str' object has no attribute 'get'` error.
**Status**:
=> Fix interpreter doc format

CHANGELOG.rst, rasa_core/agent.py, rasa_core/channels/channel.py, rasa_core/channels/custom.py, rasa_core/channels/facebook.py, rasa_core/dispatcher.py, rasa_core/evaluate.py, rasa_core/processor.py, rasa_core/tracker_store.py, rasa_core/trackers.py, rasa_core/training_utils/dsl.py, tests/test_agent.py, tests/test_policies.py, tests/test_trackers.py
See https://github.com/RasaHQ/rasa_core/issues/56. For ten python scripts (as well as some in tests folder):
"sender" is renamed as "sender_id";
"DEFAULT_SENDER" is renamed as "DEFAULT_SENDER_ID";
"sender" is set to DEFAULT_SENDER_ID (= "default")
=> issue56: 'sender' to 'sender_id', 'default' by default

rasa_core/policies/keras_policy.py
The method always returns an instance KerasPolicy instead of cls,
which means that calling load on a subclass returns the parent class.
=> Fix a bug in KerasPolicy.load

rasa_core/featurizers.py, tests/test_featurizer.py
Previously, calling `.encode` with intent features would result in an
error because `.values()` was called when `.(iter)items()` was
required. Furthermore, there was no point in treating intent features
differently.
Additionally, fix docstring and add unit test.
=> Fix bug in ProbabilisticFeaturizer encoding.

rasa_core/dispatcher.py, rasa_core/events/__init__.py, rasa_core/processor.py, rasa_core/trackers.py, rasa_core/training_utils/dsl.py, tests/conftest.py, tests/test_events.py, tests/test_processor.py, tests/test_trackers.py
- unfeaturized `BotUttered` event
- this aims to make writing conversation logs easier, as they can be retrieved from the `Tracker`, independent of output channel used (now simply retrieve all `UserUttered` and `BotUttered` events from the tracker when you write out a full log)
- the `Dispatcher` gets a `bot_message`, which holds `text` and `data` (`data` can be anything: a button, a generic element, an image)
- when the `run()` method of an action is called, all bot utterances contained in the `Action`'s `Dispatcher` are written to the tracker
=> WIP: logging all bot utterances in the tracker

rasa_core/training_utils/visualization.py
Networkx will raise an exception when acccessing neighborhood
dictionaries after modifying the graph:
```
Traceback (most recent call last):
File "visualize.py", line 9, in <module>
visualize_stories(stories, "graph.dot")
File "/home/user/Code/rasa_core/rasa_core/training_utils/visualization.py", line 302, in visualize_stories
_merge_equivalent_nodes(G, max_history)
File "/home/user/Code/rasa_core/rasa_core/training_utils/visualization.py", line 168, in _merge_equivalent_nodes
for _, succ_node, k, d in j_outgoing_edges:
File "/home/user/anaconda3/envs/frob/lib/python3.6/site-packages/networkx/classes/reportviews.py", line 799, in <genexpr>
for nbr, kd in nbrs.items() for k, dd in kd.items())
RuntimeError: dictionary changed size during iteration
```
- Copying the …
=> Copy visualization graph before modifying

rasa_core/server.py
- `python -m rasa_core.server -d models/dialogue -u models/nlu/current` is broken and gives an error: `AttributeError: 'Namespace' object has no attribute 'verbose'`
=> Fix AttributeError: 'Namespace' object has no attribute 'verbose'

rasa_core/dispatcher.py
- pass button message to event rather than forcing `None`.
=> fixes bug where button message text is set to None

CHANGELOG.rst, rasa_core/channels/channel.py, rasa_core/dispatcher.py, tests/test_dispatcher.py
- if an utterance template contains a variable that can not be filled (because it is neither the name of a slot nor did the user pass a kwarg to fill it) the code handles that gracefully instead of failing with an exception
=> Template failure

CHANGELOG.rst, rasa_core/domain.py
- e.g. if you remove an action from the domain, logs from the past might still contain that action. so we shouldn't fail here but rather just warn
- for the future we should think wether it makes sense to remove any samples that contain actions that are not part of the domain anymore.
=> Don't fail on unkown actions

rasa_core/dispatcher.py
`utter_custom_message ` is never called on the `Dispatcher` to display carousel objects in Messenger. I just added a condition that looks for an `elements` key in the message and executes `utter_custom_message ` if it finds it
=> Bug fix: utter_custom_message never called (to display carousels in Messenger)

CHANGELOG.rst, rasa_core/events/__init__.py, rasa_core/trackers.py, tests/test_tracker_stores.py
- idx stored on the tracker is not up to date after loading it from a tracker store --> instead of storing the value on the tracker we will calculate it on the fly when needed.
=> calculate restart idx on the fly

CHANGELOG.rst, rasa_core/trackers.py, tests/test_trackers.py
- When rewinding events due to a `UserUtteranceReverted` event, also rewind the previous action, which is by definition a listen
**Note:**
This seemed like the easy fix, but there may be a more elegant solution. Happy to look at alternate approaches.
- [n/a] updated the documentation
=> Fix UserUtteranceReverted event to include the prior listen

CHANGELOG.rst, data/test_trackers/tracker_moodbot.json, rasa_core/channels/console.py, rasa_core/evaluate.py, rasa_core/events/__init__.py, rasa_core/policies/ensemble.py, rasa_core/restore.py, rasa_core/run.py, rasa_core/server.py, rasa_core/tracker_store.py, rasa_core/trackers.py, rasa_core/train.py, rasa_core/utils.py, rasa_core/visualize.py, setup.py, tests/test_trackers.py, tests/test_training.py
- some formatting improvements
- added script to load a tracker that got dumped to a json file again and start a cmdline session (useful for wrong dialogue path debugging)
- will be undocumented and experimental for now - need to find out if this is a good way of debugging conversations.
=> Restores a dumped tracker from a json file, replayes the conversation

rasa_core/training/dsl.py
- reraises initial exception and ammends the file information instead of raising a new exception - makes sure a user sees what the initial failure was.
- this is ugly - but there is no other way to support py2 and py3
=> Keep original stacktrace and error msg during failed story parsing

examples/restaurantbot/data/franken_data.json
Added more data for training nlu in restaurantbot example. Insufficient examples of intents "greet" and "request_info" was giving an "UndefinedMetricWarning". Also corrected a typo in the example.
Issue #136
- Added more examples for intents "greet" (10 more) and "request_info" (13 more).
=> Added more training data for restaurantbot example

rasa_core/slots.py, rasa_core/train.py
- added warning that gets raised if a categorical slot is set to a value it has not been configured to accept
- allow to pass in validation argument to train script
=> added warnings to cat slot and allow to pass val split to train

rasa_core/channels/telegram.py
telegram integration was not working prior because the webhook required for the integration was not set previously.
Now, the telegram integration is working correctly as expected
=> webhook was not set previously

rasa_core/channels/telegram.py
- I noticed there were two log messages enter after a return in TelegramInput.set_webhook that would never get executed. I also change logger.warn with logger.warning as the warn method is set for deprecation for a while.
After looking at the code I also saw some repeated code in TelegramOutput.send_text_with_buttons that could be simplified
=> Refactor telegram channel

CHANGELOG.rst, docs/connectors.rst, rasa_core/channels/slack.py
- #371 
- Use the `slack_channel` kwarg of the `SlackClient` to choose whether to send messages back to the user or to a static channel
=> Fix Slack connector message recipient

data/test_domains/query_form.yml, rasa_core/actions/forms.py, tests/test_forms.py
- Have `FormAction` perform automatic slot filling on `utter_ask_` templates.
=> Have FormAction replace variables in utterance templates.

.gitignore, rasa_core/policies/fallback.py, rasa_core/policies/memoization.py, tests/test_policies.py
- Fallback policy could trip cirucuit breaker if subsequent intent is
predicted lower than threshold thus added the condition to prevent
predict twice in a row.
=> Gh477 fallback policy loop

examples/moodbot/Makefile
- the previous command was storing the model to `models/nlu/current/default` which doesn't correspond to the model path specified in any of the `make run`
=> fix make train-nlu

CHANGELOG.rst, rasa_core/evaluate.py
- the arguments cmdline_args.max_stories and cmdline_args.failed are in the wrong order in the call of run_story_evaluation() which leads to "failed_stories.txt" being passed as value for max_stories, therefore the evaluation fails
- this PR fixes it
fixes #545 
=> fixed error caused by switched arguments in run_story_evaluation

rasa_core/agent.py, rasa_core/policies/ensemble.py, rasa_core/train.py
- fixes #529 
- when stories get longer, it takes ages to dump the flattened stories, so we'll make this optional
=> Make dumping flattened stories optional

CHANGELOG.rst, rasa_core/processor.py
- wrap initialisation of backgroundscheduler in a try/ excepy
- allows rasa core to run in docker containers without first setting the system timezone (e.g. binderhub, jupyterhub, colaboratory)
=> wrap scheduler init in try/except

CHANGELOG.rst, rasa_core/domain.py, rasa_core/server.py, rasa_core/utils.py, tests/test_domain.py
- create domain from yaml string
- create yaml string from domain
- expose endpoint for fetching domain yaml
=> Domain API endpoint

CHANGELOG.rst, rasa_core/processor.py, tests/test_trackers.py
- fixed event order for bot utterances, executed actions are now always logged before any bot utterances are logged that that action created
=> fixed event order for bot utterances

Dockerfile
- Use `--no-cache-dir` in `pip install` to reduce image size
Managed to reduce more than 100Mb in local tests
=> Reduced Docker image size: removed pip cache

data/test_stories/stories.md, data/test_stories/stories_checkpoint_after_or.md, rasa_core/training/structures.py, tests/test_dsl.py
- remove redundant generated `OR` checkpoints even if there are no cycles in the stories
- remove the whole story step if such redundant generated `OR` checkpoints were the only checkpoints
=> Fix removing generated OR checkpoint if it is the only one checkpoint

CHANGELOG.rst, docs/api/events.rst, docs/migrations.rst, docs/server.rst, rasa_core/events/__init__.py, tests/test_events.py
- list all events and their json formats on the events help page
- removed documentation for `/parse` endpoint, as it does not exist anymore (fixes #924)
- added tests for the json parsing
=> Improved event docs and removed outdated server docs

CHANGELOG.rst, docs/policies.rst
=> add EmbeddingPolicy to changelog

docs/interactive_learning.rst
- Current documentation about Interactive Learning seems outdated as the rasa_core.run does not handle this funcionality and thus does not have the --interactive and --stories-out parameters. Proper command execution should be:
```
python -m rasa_core.train \
--online --dump_stories \
-d domain.yml -s stories.md \
-o models/dialogue \
--endpoints endpoints.yml 
```
=> Update interactive learning docs #935

docs/installation.rst
Added the starterpack to the docs. I didn't include the github clone function, because I want people to open the Github, see the link to the dataset and also see the gif of the bot they will be able to build. Chances are if they just going to clone it and ignore the Readme, they will get the data from the forum. Let me know what you think.
=> added starter-pack

CHANGELOG.rst, docs/connectors.rst, rasa_core/channels/__init__.py, rasa_core/channels/socketio.py, rasa_core/run.py, requirements.txt, setup.py, tests/test_channels.py
- added socketio channel implementation
=> added socketio channel implementation

rasa_core/run.py, rasa_core/training/online.py
If you wrap `run.serve_application`  or `training.online.serve_application` in a custom CLI tool (or any other kind of application) and use console I/O, this application will currently not exit cleanly on `SIGINT` as the child processes summoned by rasa are not running as daemons and at the same time noone is listening to any signals in order to shut them down manually.
This means it currently requires two SIGINTs for the parent application to exit (which unfortunately apparently also kills/freezes Conda on Windows on the second signal).
To fix this condition, have the child processes run daemonized (as already done in  `agent.start_model_pulling_in_worker`).
=> Daemonize threaded processes used for console I/O

CHANGELOG.rst, docs/interactive_learning.rst
- Software 2.0 hyperlink in the Interactive Learning documentation went to the Tesla homepage, now it directs to a blogpost by Andrej Karpathy on Medium
- [] made PR ready for code review
- [] added some tests for the functionality
=> Added more informative link to docs

docs/interactive_learning.rst, rasa_core/train.py, rasa_core/training/interactive.py, tests/test_examples.py, tests/test_interactive.py
- fixes https://github.com/RasaHQ/rasa_core/issues/1057
- changes every occurrence of 'online' learning in the codebase to 'interactive', except within the policy / ensemble where online training is really the correct term.
=> rename online to interactive learning #1057

CHANGELOG.rst, data/test_trackers/tracker_moodbot.json, docs/_static/spec/server.yml, rasa_core/events/__init__.py, rasa_core/processor.py, tests/test_events.py, tests/test_server.py
- return action confidence and policy when serializing `ActionExecuted` events. fixes #623
=> return action confidence when serialising. fixes #623

CHANGELOG.rst, rasa_core/domain.py, rasa_core/evaluate.py, rasa_core/featurizers.py, rasa_core/policies/ensemble.py, rasa_core/policies/fallback.py, rasa_core/policies/keras_policy.py, rasa_core/policies/memoization.py, rasa_core/trackers.py, rasa_core/training/dsl.py, rasa_core/training/interactive.py, rasa_core/training/structures.py, rasa_core/utils.py, tests/test_dialogues.py, tests/test_dsl.py, tests/utilities.py
- use utf8 everywhere for file IO. fixes #1041
- did not find a way to test this, as there doesn't seem to be a reliable way to change the default encoding used by io.open.
=> Use utf8 everywhere for file IO. fixes #1041

CHANGELOG.rst, rasa_core/policies/ensemble.py
- fixes #1104
- Added date to _persist_metadata() function of base policy ensemble
=> Add training date and time to policy metadata when persisting  Fixes #1104

CHANGELOG.rst, rasa_core/channels/facebook.py
- facebook channel has been broken since 0.11.6 due to a missing `name()` in the Messenger class
- fixes #1125 
=> Messengerfix

docs/interactive_learning.rst
The documentation doesn't mention how to use a trained nlu model for intent classification with interactive learning. Although it is an intuitive command, people might not be able to figure it out so easily and just stay confused about why the intents from their model are not showing up.
- ...
=> Update Interactive learning documentation

rasa_core/evaluate.py, rasa_core/server.py
- partial tracker uses correct user utterance and correct action, regardless of prediction
- entities are excluded from evaluation metrics
- the failed stories output prints user messages in end-to-end form, regardless of whether prediction was correct or not
=> Evaluation improvements

docs/index.rst, docs/tracker_stores.rst
**Motivation**:
- As soon as pull request https://github.com/RasaHQ/rasa_core/pull/1048 is merged, it will be possible to use different tracker stores through configuration in the endpoints configuration. 
To make this feature useable for developers, they need documentation on that.
- closes https://github.com/RasaHQ/rasa_core/issues/1195
- Added a subsection within the `developer` section which informs about the currently existing tracker store types and how to configure them
- Added a subsection within the `developer` section which explains how to implement a custom tracker store.
=> #1195 - add documentation on how to use different tracker stores

CHANGELOG.rst, rasa_core/broker.py, rasa_core/run.py, rasa_core/server.py
- https://github.com/RasaHQ/rasa_core/issues/1277
- If no queue is present for the broker configuration, it overwrites the default queue with `None`. This should not be the case, the default value should be preserverd
=> pass correct tracker store object #1277

docs/server.rst, rasa_core/agent.py
- Server won't trigger an error message in case of 304 when trying to pull a model
- [ x] made PR ready for code review
- [ x] updated the documentation
=> response code could be 304 when model is up to date

rasa_core/policies/keras_policy.py
The Keras policy appears to be using the epochs parameter for both epochs and batch_size.  This appears to be incorrect (to me).
=> Fix batch_size parameter in Keras policy

rasa_core/policies/ensemble.py, tests/test_config.py
- get_featurizer_from_dict and get_state_featurizer_from_dict are called like classmethods in from_dict, but classmethod decorator is missing.
- Instead of get_state_featurizer_from_dict, get_featurizer_from_dict is called twice
- Added `@classmethod` to both methods
- Changed get_featurizer_from_dict to get_state_featurizer_from_dict when state featurizer is created
=> Ensemble.from_dict not working

docs/docker_walkthrough.rst
- The username parameter for tracker_store should be 'username' not 'user' as discussed here (#1332)
=> Changed tracker_store param 'user' to 'username' in docs

examples/restaurantbot/policy.py, rasa_core/channels/botframework.py, rasa_core/channels/mattermost.py, rasa_core/channels/telegram.py, rasa_core/channels/twilio.py, rasa_core/domain.py, rasa_core/processor.py, rasa_core/server.py, rasa_core/training/interactive.py, requirements.txt, tests/test_interactive.py
- do not add actions if they are forms in old domain (fixes #1370)
- do not add default actions (fixes #1354)
- make warning about new action creation a question to improve visibility
- improve cleaning of newly written domain file
- fixes #1218
=> Fix new interactive training feature to add custom actions to domain

rasa_core/training/interactive.py
When [passing an event](https://github.com/RasaHQ/rasa_core/blob/0.12.2/rasa_core/training/interactive.py#L522) like BotUttered("only a text message") to format_bot_output this will throw as [the dict being created](https://github.com/RasaHQ/rasa_core_sdk/blob/47106d959767148d15b328a3a38a95cd697e0616/rasa_core_sdk/events.py#L26-L33) will contain a data key, but its value is None. This requires an additional check for this case before proceeding as `get` might as well return `None`.
=> In `format_bot_output`, consider case where data key is present on dict, but None

rasa_core/training/interactive.py
Added a quick fix for FileNotFoundError handling in Python 2.x
- Overwriting FileNotFoundError with IOError for Python 2.x
=> FileNotFoundError does not exist in Python 2.x

rasa_core/train.py, rasa_core/training/generator.py, rasa_core/training/structures.py
This picks up #1390. I tried using `--debug_plots` but ran into two issues:
- a pdf file is exported, but it seems to be a HTML document
- when opening this document in a browser it will not display anything, throwing:
```
dagre-d3.min.js:26 Uncaught TypeError: shape is not a function
at SVGGElement.<anonymous> (dagre-d3.min.js:26)
at Selection.selection_each [as each] (d3.v4.js:1185)
at createNodes (dagre-d3.min.js:26)
at fn (dagre-d3.min.js:90)
at Selection.selection_call [as call] (d3.v4.js:1149)
at drawGraph (story_blocks_connections.html:114)
at story_blocks_connections.html:916
```
I managed to fix both issues and can use the patched version as expected.
- Change the file extension of `debug_plots` so that it matches the output (it's a HTML file, not a PDF)
- …
=> Fix output of training with --debug_plots

docs/api/policy.rst
For implementing custom Policy classes
It'd be useful to add these methods to the API documentation - to use Agent.load and Agent.persist with a custom policy, you have to implement these methods in your custom Policy, but this isn't documented anywhere yet
=> Add documentation for Policy.load and Policy.persist

rasa_core/channels/facebook.py
- Currently, Rasa overrides custom buttons to be always of the type "postback" even if the type is different and being provided. Changed this behavior to allow other button types (web_url etc.)
- fixes #1417 
=> Do not override custom button type if provided (#1416)

CHANGELOG.rst, rasa_core/training/interactive.py
According to #1339, in-memory tracker stores load previous sessions during interactive learning.
- Make initial sender_id random
=> Randomized initial sender_id in interactive.py to allow fresh training sessions upon start

CHANGELOG.rst, rasa_core/channels/channel.py, rasa_core/channels/console.py, rasa_core/training/interactive.py, tests/test_interactive.py
@akelad @tmbo : Sorry, I somehow messed up the other [PR](https://github.com/RasaHQ/rasa_core/pull/1344) request such that it got closed and cannot reopen it again. Summarizing the key issues again here: 
Custom buttons and elements couldn't be displayed in interactive learning and console channel output.
- Adjusted button to string representation to add custom attributes as JSON object after current string
- Added element to string representation for custom messages accordingly
- Adjusted test cases
- Added element to string representations to console and interactive learning output 
=> Changing button / element representation to allow for customized buttons in cmdline

docs/server.rst
Typo in the documentation on page server.rst. The command for running the rasa core had missing backslash.
- Add backslash
- [ x ] updated the documentation
=> Typo in server.rst docs

CHANGELOG.rst, rasa_core/training/interactive.py
- if NLU classification returned `None`, directly ask a user for a correct intent
- fixes #1488 
- fixes #1465 
=> do not allow a user to confirm None intent in interactive learning

CHANGELOG.rst, rasa_core/policies/ensemble.py, rasa_core/utils.py
=> Add tf and sklearn version info to policy metadata

rasa_core/channels/console.py
- fix printing multiple `Buttons:` in cmd
=> fix printing multiple `Buttons:` in cmd

CHANGELOG.rst, rasa_core/constants.py, rasa_core/policies/fallback.py, rasa_core/policies/memoization.py, tests/test_policies.py
- Change memoization confidence value to 1.1 so that it actually overrides ML policies when they have a confidence of 1.0 (in fact i feel like it used to be like this, not sure if/when we changed it back to 1.0)
- Increase form policy/fallback policy confidence values so they override the memo policy
=> Change Memoization confidence value to 1.1

rasa_core/actions/action.py, tests/test_actions.py
- part of fix for  #1568
With this PR the call to the action servers includes the rasa_core version number. This allows the server to check and compare the versions.
=> report core version in remote action call

CHANGELOG.rst, rasa_core/server.py
When reloading models with `/model` endpoint domain will also be reloaded (not only policy ensemble).
Related issue: #1594
=> Reload model with domain

CHANGELOG.rst, rasa_core/channels/channel.py, rasa_core/events/__init__.py, rasa_core/processor.py, tests/test_channels.py, tests/test_processor.py
- closes  #1228 
The UserMessage class can be intialized with a message_id, if this argument is not given an ID is generated.
The UserUttered event has a corresponding attribute which is assigned the message_id of a UserMessage by the tracker.
=> Add identifier to messages

CHANGELOG.rst, rasa_core/policies/ensemble.py, tests/test_ensemble.py
- fixes https://github.com/RasaHQ/rasa_core/issues/1576
- fixes https://github.com/RasaHQ/rasa_core/issues/1575
- raise `InvalidPolicyConfig` error in case the policy in the module could not be loaded, the `policies` key is empty or not there
- ~[ ] updated the documentation~
=> improve error message in case policy module could not be loaded

rasa_core/channels/channel.py, tests/test_channels.py
- properly handle if `route` is set to `None` for a blueprint of an input channel when registering
=> handle passing in None for a channels route

CHANGELOG.rst, rasa_core/training/interactive.py
- domain was created with invalid properties when dumping from interactive learning which lead to an exception (`AttributeError: 'list' object has no attribute 'items'`)
- fixes #1194
=> properly instantiate domain properties

docs/docker_walkthrough.rst
- Path to __ init__.py altered so now Python can import it properly
- Two typos are corrected
=> Fix of __init__py path in doc and two typos

binder/requirements.txt
Fixes: https://github.com/RasaHQ/rasa_core/issues/1543
- Quickstart throws a warning that service_identity is missing. Updated binder requirements to include it.
=> update binder requirements

.travis.yml, CHANGELOG.rst
To fix #1662 
- Starter pack tests moved into first Travis test stage
- Tests only run on new version branches and `master`
=> Test starter pack tests on new version builds only

docs/connectors.rst
- Changed slack_channel name specification. When channel name is specified as '@channel_name' bot messages don't get posted on a channel. According to [Slack Web API](https://api.slack.com/methods/chat.postMessage#channels) the channel should be specified either as a channel id or as a channel name in a form of '#channel_name'.
=> changed slack_channel name specification

CHANGELOG.rst, docs/_static/spec/server.yml, rasa_core/server.py, rasa_core/training/interactive.py, tests/test_server.py
#1707 
- Sorting the actions in `score ` array returned from HTTP API endpoint :- `/conversations/{sender_id}/predict` 
- Remove the sorting logic from `training.interactive._request_action_from_user() `
@tmbo I have added-deleted the sort from the aforementioned places, what do you think? Also, I am confused about writing new tests for these changes, the tests already in test_server.py should suffice right? or am I missing something?
=> WIP: sort the scores array in server.py

CHANGELOG.rst, docs/tracker_stores.rst
If anyone has different database name associated with the user’s credentials then they have to specify this parameter.
- auth_source param was missing in the documentation for Tracker store for Mongo DB.
=> Adding auth_source param in Mongo DB Tracker Store documentation.

docs/evaluation.rst, docs/fallbacks.rst, docs/policies.rst
- Update docs to remove out-of-date information about where to pass arguments to certain policies (i.e. command line or `agent.train()` instead of the policy configuration file)
- Fix incorrect output file in training command
- Part 1 of #1678
=> 0.13.x update docs

CHANGELOG.rst, rasa_core/training/visualization.py
Fixes https://github.com/RasaHQ/rasa_nlu/issues/2995
Under certain circumstances we were passing the message parse data to the node label during interactive learning visualization, which (since this is a dictionary) was causing fatal errors.
- Use message intent name instead of the parse data as the graph node label
=> Extract message intent instead of setting the node with a dict when using visualization
