docs/_templates/layout.html

added ga tagging

---

docs/domains.rst
docs/index.rst
docs/no_python.rst

- adds page in docs for users who aren't comfortable with / able to use python

add page for non-python devs

---

CHANGELOG.rst
examples/hello_world/run.py
rasa_core/agent.py
rasa_core/policies/keras_policy.py
rasa_core/processor.py
rasa_core/server.py

- a  couple of minor style fixes
- fix http bug (wrong state if action listen is not confirmed by api user) #42 
- small dropout in keras model to make it overfit a bit less

Minor fixes

---

CHANGELOG.rst
rasa_core/domain.py
rasa_core/run.py
rasa_core/server.py
rasa_core/utils.py

- small script to load a trained dialogue model with a nlu model to run a bot listening on an input channel (currently cmdline or facebook)

'run' script for easy model running

---

CHANGELOG.rst
data/validation/domain_schema.yml
docs/domains.rst
examples/remote/models/current/domain.yml
examples/restaurant_domain.yml
rasa_core/dispatcher.py
rasa_core/domain.py
rasa_core/policies/ensemble.py
requirements.txt
setup.py
tests/test_dispatcher.py
tests/test_domain.py
tests/test_domain_spec_dm.py

- validates the domain yaml file and raises an exception if the file has an improper format (prevents strange errors if e.g. the utterance templates are an array instead of a map)

Domain validation

---

examples/moodbot/data/nlu.md

- Changed the "greeting" intent in nlu.md file to "greet". The intent is referred as "greet" in domain and story files.

Fix for issue #63 - Moodbot tutorial

---

rasa_core/trackers.py

Minor bug fix. See https://github.com/RasaHQ/rasa_core/issues/67

[issue67] self.latest_action_name = None

---

rasa_core/channels/facebook.py

- Add warnings to log if fb_secret/fb_verify is incorrect

Fb logging

---

rasa_core/train.py

- Explicitly mark integer arguments for training as integers

Specify types for integer arguments

---

docs/tutorial_basics.rst
examples/remotebot/nlu_model_config.json

- Updated the data path in 'nlu_model_config.json' for the remotebot example to point to the correct file.
Fixes #73 
Fixes #70

Fix for issue #69 & #73

---

rasa_core/server.py

- Specify type for port number
- [x ] made PR ready for code review

Specify integer as type for port number argument

---

docs/tutorial_basics.rst

Grammatical typo

---

docs/tutorial_interactive_learning.rst

Broken link fixed

---

CHANGELOG.rst
docs/tutorial_basics.rst
examples/moodbot/Makefile
examples/moodbot/data/nlu.md

- more nlu examples
- properly fit keras model by using more epochs (otherwise there isn't enough training data and the model will not fit the stories properly after the default 100 epochs)

properly fit dialogue model and more nlu examples

---

README.md
docs/installation.rst

Tweak docs

---

rasa_core/training_utils/dsl.py

- Add line number to unknown intent warning to aid in debugging

Add line number to unknown intent warning

---

rasa_core/server.py

- protect server resources with an auth token like in rasa nlu

added possibility to specify auth token to protect server

---

rasa_core/featurizers.py
rasa_core/slots.py

Float slot

---

examples/moodbot/data/nlu.md

The accuracy was not very good. In fact it responded to "I'm sad" with "Great, carry on".
- ...

added some more training data to the moodbot

---

rasa_core/actions/factories.py
rasa_core/dispatcher.py
rasa_core/policies/memoization.py
rasa_core/policies/online_policy_trainer.py
rasa_core/policies/trainer.py
rasa_core/run.py
rasa_core/training/dsl.py
rasa_core/training/structures.py

- remove unused import statements

import cleanups

---

CHANGELOG.rst
dev-requirements.txt
rasa_core/events/__init__.py
rasa_core/featurizers.py
rasa_core/slots.py
rasa_core/trackers.py
setup.py
tests/test_server.py

- adds timestamp for `UserUttered` and `BotUttered` events
- adds `latest_message_time` attribute to tracker

timestamps

---

CHANGELOG.rst
README.md
docs/connectors.rst
docs/index.rst
docs/migrations.rst
examples/moodbot/credentials.yml
rasa_core/channels/channel.py
rasa_core/channels/facebook.py
rasa_core/channels/rest.py
rasa_core/run.py
requirements.txt
setup.py

- remove old pymessenger library and use fbmessenger instead.
- added a couple type annotation and comments here and there

switched to fbmessenger library instead of pymessenger

---

rasa_core/trackers.py
tests/test_trackers.py

- added function to reset a tracker to a previous state using a timestamp

Time travel a trackers state

---

rasa_core/actions/factories.py

- exception handler returned none if a third party dependency is not found instead of raising again

properly raise exception on unknown package

---

rasa_core/trackers.py

- use full list of events in timetravel so we can go back to before that last restart

allow timetravel to before last restart

---

docs/tutorial_supervised.rst
examples/restaurantbot/bot.py
examples/restaurantbot/policy.py

- moved policy to own model to allow it getting persisted properly (otherwise it will get persisted with `__main__` as a module path, which can not be loaded consistently)

moved polciy to own model to allow it getting persisted properly

---

docs/installation.rst
docs/tutorial_basics.rst

fixed docs according to issue #220

---

CHANGELOG.rst
rasa_core/channels/facebook.py
requirements.txt
setup.py

- update messenger to version 5.0.0 (from 4.3.1)

updated fb messenger

---

docs/tutorial_supervised.rst

Fixed docs

---

CHANGELOG.rst
docs/http.rst
rasa_core/channels/direct.py
rasa_core/processor.py
rasa_core/server.py
tests/test_agent.py
tests/test_dispatcher.py
tests/test_examples.py
tests/test_processor.py
tests/test_trackers.py

- addresses https://github.com/RasaHQ/rasa_core/issues/119

add direct endpoint to rasa core http server

---

docs/_templates/layout.html

support script

---

README.md

update urls in README

---

CHANGELOG.rst
data/test_multifile_stories/stories_part_1.md
data/test_multifile_stories/stories_part_2.md
docs/stories.rst
rasa_core/agent.py
rasa_core/evaluate.py
rasa_core/policies/online_policy_trainer.py
rasa_core/policies/trainer.py
rasa_core/train.py
rasa_core/training/__init__.py
rasa_core/training/dsl.py
rasa_core/visualize.py
tests/test_domain.py
tests/test_dsl.py
tests/test_evaluation.py
tests/test_policies.py
tests/test_trackers.py

- instead of specifying a single file for stories, this allows to load stories from a directory of story files
- in the future we can think about specifying multiple files directly (instead of a folder) - but this was easier to do for now

implementation of support for loading stories from multiple files

---

rasa_core/server.py

- importing from `rasa_nlu.server` causes its `main` to be executed

don't import rasa_nlu.server

---

rasa_core/server.py

- in klein (unlike flask) `request.args.get` returns a list rather than a single item

Fix bool arg

---

docs/connectors.rst
examples/moodbot/mattermost_credentials.yml
rasa_core/channels/mattermost.py
rasa_core/run.py
requirements.txt

- Adding in the mattermost connector including the documentation

Mattermost connector

---

rasa_core/interpreter.py

wip fix interpreter for rasa nlu 0.12

---

setup.py

Add mattermost to setup.py

---

.travis.yml

- as far as I can tell these lines don't do anything except slow down the builds
- tests pass fine without them

remove redundant steps from travis build

---

data/test_dialogues/enter_name.json
data/test_domains/default_with_slots.yml
tests/test_trackers.py

- fixes test that was occasionally failing on python 3.5

Fix py3.5 test

---

docs/scheduling.rst

- fix docs to reflect current naming for reminder event
fixes issue #349

updated docs for renaming Reminder to ReminderScheduled

---

CHANGELOG.rst
rasa_core/server.py
rasa_core/tracker_store.py

- creates an endpoint to list running conversations

List conversations

---

docs/http.rst

- it's not experimental anymore so we should remove the warning

remove experimental warning for HTTP server

---

CHANGELOG.rst
docs/connectors.rst
examples/moodbot/twilio_credentials.yml
rasa_core/channels/twilio.py
rasa_core/run.py
requirements.txt
setup.py

Twilio connector

---

rasa_core/server.py

- We need a full set of headers for CORS to work properly with klein

add more cors headers

---

docs/index.rst
docs/installation.rst

- add links to colab notebook so users can try out the Rasa Stack without installing stuff

add references to colab notebook

---

rasa_core/policies/augmented_memoization.py
rasa_core/policies/memoization.py

- some of the functions were quite hard to review so I tried to clean them up a bit
- e.g. use early return so
```
def f(a):
if a is None:
return 1
...
```
instead of 
```
def f(a):
result = 1
if a:
...
return result
```

WIP: Simple generator review

---

data/test_domains/travel_form.yml
rasa_core/actions/forms.py
tests/test_forms.py

- fixes #407 (though not a super general solution) cc @hotzenklotz

dont double-extract slots

---

docs/index.rst
docs/installation.rst

fix colab link

---

docs/tutorial_basics.rst

- add starter pack to the moodbot tutorial

add starter pack to tutorial

---

docs/connectors.rst

- Minor telegram setup issue in docs

minor telegram setup issue

---

rasa_core/channels/rest.py

Fix gevent WSGIServer import

---

docs/patterns.rst

- Add missing comma in Fallback Policy example code on Doc

[#478] Add missing comma in Fallback Policy example code

---

docs/connectors.rst

- removed a duplication of the slack docs
- fixed spacing in notes for telegram/twilio

fix minor connectors docs issues

---

CHANGELOG.rst
docs/migrations.rst
rasa_core/domain.py

- have the list slot actually store a list of entities
- fixes #171 

list slot fix

---

rasa_core/events/__init__.py
rasa_core/policies/memoization.py
rasa_core/training/dsl.py

- add ability to read `- slot{"city": "text", "state": "text"}` from stories

Read multiple slots from stories

---

data/test_dialogues/nlu_dialogue.json
rasa_core/featurizers.py
rasa_core/policies/augmented_memoization.py
rasa_core/policies/ensemble.py
rasa_core/policies/memoization.py
tests/test_examples.py
tests/test_featurizer.py
tests/test_policies.py

- add `binary_intent_prob` flag to `TrackerFeaturizer`. If it is set to `True` (default behavior), binarize intent probabilities on the `states` level
- merge `Binary-` and `ProbabilisticSingleStateFeaturizer` together

Fix featurizers

---

docs/conf.py

- Update copyright year from 2017 to 2018

Update copyright year in documentation

---

CHANGELOG.rst
rasa_core/server.py

- `agent()` method needs to be evaluated at every call in the decorator

Check agent loading

---

CHANGELOG.rst
rasa_core/policies/online_trainer.py

- fixes #415
- set default path for online learning data persistence

set default file if user doesn't provide file after online learning

---

rasa_core/server.py

Added comments in server.py

---

rasa_core/agent.py

Added comments to agent.py

---

rasa_core/featurizers.py
rasa_core/trackers.py
rasa_core/training/generator.py

Caching for featurizer

---

rasa_core/agent.py
rasa_core/featurizers.py
rasa_core/policies/fallback.py
rasa_core/policies/memoization.py
rasa_core/policies/policy.py
rasa_core/trackers.py
rasa_core/train.py
tests/conftest.py
tests/test_examples.py
tests/test_training.py

- fix: keras policy was not picking max_history parameter

Make keras policy use max_history parameter in train.py

---

rasa_core/trackers.py

- ...
- [ X] made PR ready for code review
- [] updated the documentation

Small typo in comments

---

.travis.yml
docs/conf.py

build docs from master base and don't whitelist docs_reorg branch

---

rasa_core/policies/ensemble.py
rasa_core/policies/fallback.py

- give the fallback policy a confidence of 1.1 so it overrides the memo and any other policy (previously the fallback action would not get executed because other policies also had a confidence of 1.0)

fix fallback policy

---

rasa_core/policies/ensemble.py
rasa_core/policies/fallback.py

- make same change to 0.9.x as we did to master

fix fallback for 0.9

---

rasa_core/policies/fallback.py

- Always predict action_listen after fallback action

predict action listen after fallback

---

docs/fallbacks.rst
rasa_core/policies/fallback.py

- force action_listen to be predicted after fallback action

fallback fix

---

CHANGELOG.rst
docs/fallbacks.rst
docs/migrations.rst
examples/moodbot/domain.yml
rasa_core/actions/action.py
rasa_core/domain.py
rasa_core/policies/ensemble.py
rasa_core/policies/fallback.py
rasa_core/version.py
tests/test_actions.py
tests/test_domain.py
tests/test_dsl.py
tests/test_remote.py

- Create a new default action ActionFallback

New fallback action

---

.travis.yml
dev-requirements.txt

- use publicly available docs theme package
- developers can build docs locally

use publicly available docs theme package

---

docs/conf.py
docs/connectors.rst
docs/slotfilling.rst

- some docs improvements
- whitelist new major version for docs build

Docs theme gcs

---

.travis.yml

- otherwise PRs off old branches can overwrite the docs! 

only build and push docs on master (incl PRs)

---

CHANGELOG.rst
rasa_core/channels/rasa_chat.py

New chat input channel

---

rasa_core/run.py

- fixes #780 
- always return an interpreter when loading model locally
- switch params around for RasaNLUHttpInterpreter

Fix loading of nlu model

---

CHANGELOG.rst
docs/domains.rst
rasa_core/domain.py
rasa_core/schemas/domain.yml
tests/test_domain.py

- allow user to specify a list of intents in the domain file for which entities should be ignored. These entities will only be ignored if they do not have a featurized slot of the same name.

Unfeaturized entities for specific intents

---

docs/domains.rst

- fix missing indentation in unfeaturized entities docs

fix indentation mistake

---

.travis.yml
dev-requirements.txt
docs/quickstart.rst

- the 'interactive chat' in the quickstart now actually shows the chat messages in chronological order .

Improve quickstart

---

rasa_core/channels/rasa_chat.py
rasa_core/remote.py

- added respond to remote core

add respond to remote core

---

CHANGELOG.rst
docs/api/interpreter.rst
rasa_core/interpreter.py
tests/test_interpreter.py

Fixes #689
- Add intent confidence support in `RegexInterpreter`

Add intent confidence to RegexInterpreter

---

README.md

Updated README.md file: changed the Gitter links to Rasa Community Forum links.

Add Rasa Community Forum links to README.md

---

docs/quickstart.rst

inform user that cells in quickstart aren't independent

---

.github/stale.yml

- add the issue bot that automatically closes stale issues

add an issue bot

---

binder/requirements.txt

- fixes https://github.com/RasaHQ/rasa_core/issues/869

add requirements for quickstart

---

docs/index.rst
docs/support.rst

Added 'support' section to the docs

Add support channels to the docs

---

rasa_core/actions/action.py
rasa_core/run.py

- make utter_template get `kwargs`
- matplotlib logger set to warning

small fixes

---

docs/quickstart.rst

- also use better rendering of messages for 2nd 'talk to bot' in quickstart

properly render chat in 2nd chat-with-bot in quickstart

---

rasa_core/server.py
tests/test_server.py

- add predict endpoint for a list of events

rebased predict endpoint on dispatcher

---

rasa_core/remote.py

- increase wait time between model upload attempts

increase wait time between model upload attempts

---

docs/connectors.rst
examples/moodbot/Makefile
examples/moodbot/rocketchat_credentials.yml
rasa_core/channels/rocketchat.py
rasa_core/run.py
requirements.txt

Signed-off-by: Izabela Cardoso <cizabelacristina@gmail.com>
Signed-off-by: Matheus Miranda <matheusmirandalacerda@gmail.com>
- Added RocketChat connector 
- Updated docs/connector.rst 
- Updated CHANGELOG.rst

Add RocketChat connector

---

docs/migrations.rst

- Update migration instructions for running bot on cmdline

Update migration instructions for running bot on cmdline

---

.github/no-response.yml

- If an issue labeled with "more-information-needed" hasn't been responded to within 14 days, the issue will be automatically closed

add noresponse bot

---

rasa_core/policies/memoization.py

- augmented memoization created to many debug logs, that didn't contain the relevant information

clear debug logs for augmented memoization policy

---

rasa_core/run.py

Fixes #955 
- [] added some tests for the functionality
- [] updated the documentation
- [] updated the changelog

Fixes issue where logs used default port and not the specified port

---

docs/api/agent.rst
docs/api/events.rst
docs/api/featurizer.rst
docs/api/interpreter.rst
docs/api/policy.rst
docs/api/slots_api.rst
docs/api/tracker.rst
docs/architecture.rst
docs/brokers.rst
docs/changelog.rst
docs/connectors.rst
docs/customactions.rst
docs/debugging.rst
docs/docker.rst
docs/domains.rst
docs/evaluation.rst
docs/fallbacks.rst
docs/feedback.inc
docs/index.rst
docs/installation.rst
docs/interactive_learning.rst
docs/livechat.html
docs/migrations.rst
docs/policies.rst
docs/quickstart.rst
docs/responses.rst
docs/server.rst
docs/slotfilling.rst
docs/slots.rst
docs/stories.rst

- Added support channels: live chat and the links to Community Forum and Github issues.

added support channels

---

rasa_core/train.py

make domain arg optional

---

CHANGELOG.rst
data/test_trackers/tracker_moodbot.json
rasa_core/events/__init__.py
rasa_core/trackers.py
tests/test_trackers.py

- use consistent followup attribute naming in the tracker

Fixed followup attribute naming

---

docs/conf.py

- don't match forked master branches

fix branch whitelist

---

docs/fallbacks.rst

Updated the fallback doc, with correct action name

---

CHANGELOG.rst
rasa_core/slots.py
tests/test_slots.py

- Added an extra feature for un-set booleans
- Fixes issue #691

Booleanslotfix

---

CHANGELOG.rst
dev-requirements.txt
setup.py

Removepytestservices

---

CHANGELOG.rst
rasa_core/slots.py
rasa_core/version.py
tests/test_slots.py

- updated version & changelog
- undid booleanslot fix on master as it is breaking, will reapply afterwards

preparing next minor release

---

CHANGELOG.rst
data/test_trackers/tracker_moodbot.json
rasa_core/channels/botframework.py
rasa_core/channels/callback.py
rasa_core/channels/channel.py
rasa_core/channels/facebook.py
rasa_core/channels/mattermost.py
rasa_core/channels/rocketchat.py
rasa_core/channels/slack.py
rasa_core/channels/socketio.py
rasa_core/channels/telegram.py
rasa_core/channels/twilio.py
rasa_core/events/__init__.py
rasa_core/processor.py
rasa_core/trackers.py
tests/test_actions.py

- `UserMessage` and `UserUttered` receive new attributes for input channel used

Store input_channel in UserMessage and UserUttered

---

CHANGELOG.rst
rasa_core/version.py

- Release minor version `0.11.6`

Minor release 0.11.6

---

CHANGELOG.rst
rasa_core/channels/rocketchat.py

Channel: rocketchat
- Fix parameter name
- Add custom message method for sending attachments

channel rocketchat: fix, implement custom message

---

.travis.yml

- Had a bug in the condition and also it triggered while the pull request merge was tested. It should however only trigger once the PR has been merged in.

fixed condition + only trigger on merge into master

---

CHANGELOG.rst
rasa_core/channels/channel.py
tests/test_channels.py

- user different blueprint names for the different channels

Rest rasa channels

---

CHANGELOG.rst
rasa_core/processor.py
tests/test_processor.py

- Cancel reminders after restarted events

Cancel reminders after restarted events

---

rasa_core/agent.py
tests/conftest.py
tests/test_agent.py

recreate PR #1091 against 0.11.x

---

rasa_core/server.py
rasa_core/utils.py
tests/test_server.py

Cherry pick #1068

---

setup.py

- Updated old community link inside the setup.py file

updated community link

---

CHANGELOG.rst
docs/connectors.rst
examples/moodbot/credentials.yml
rasa_core/run.py
tests/test_run.py

- Allow custom connector argument on run scripts ``--connector``

Allow custom connector argument

---

CHANGELOG.rst
rasa_core/server.py
tests/test_server.py

We should query user information from the user object rather than at the root of the data encoded in the JWT

Fixed incorrect JWT parsing in rasa_core server

---

setup.py

- pins tensorflow version, bc minor version update from tf actually breaks keras model compatibility
- fixes #1117 

pin tensorflow version 

---

rasa_core/train.py

- do not allow `--finetune` and `--core` together for interactive learning
- prevents errors in #1114

raise error if --finetune flag and pretrained model --core is given

---

rasa_core/train.py

pass action and nlg endpoints to agent.load

---

rasa_core/server.py
tests/test_server.py

- cherry-picked commits from fix in master
- will need another minor release for this

Fix jwts 0.11

---

data/test_stories/stories_restart.md
rasa_core/training/generator.py
tests/test_training.py

fix putting `action_restart` in the stories break training #906

---

tests/test_channels.py

the server_forever was set to True for keeping the server running.
- ...

Fix serve_forever=True for all tested channels

---

examples/nlg_server/nlg_server.py

- Consistent arguments for domain loading in NLG server example.

Consistent arguments for domain loading

---

docs-requirements.txt

bump docs theme version 

---

.travis.yml

- configure travis to do the pep8 compliance checks on all directories

perform pep8 on all directories

---

CHANGELOG.rst
Dockerfile
docker/docker-compose.yml
docs/installation.rst
entrypoint.sh

**Motivation**:
Issue: https://github.com/RasaHQ/rasa_core/issues/845
- remove nlu from rasa core Dockerfile
- add docker compose file which straps together core, nlu, core sdk and duckling

Core only dockerfile

---

docs/_static/spec/server.yml
rasa_core/evaluate.py
tests/test_evaluation.py
tests/test_server.py

Return actions, predictions, confidences and policies in rasa_core.evaluate

---

requirements.txt
setup.py

- requests 2.18 has a security vulnerability, hence the update to 2.20

Updated requests library due to security vulnerability

---

.travis.yml

download and install rasabaster package in separate steps

---

docs/server.rst

Typo in models endpoint yaml example

---

CHANGELOG.rst
docs/server.rst

- follow up from https://github.com/RasaHQ/rasa_nlu/issues/1476 and https://github.com/RasaHQ/rasa_nlu/pull/1477
- add some documentation on how to connect Rasa NLU to Rasa Core

add endpoint documentation

---

CHANGELOG.rst
docs/connectors.rst

Missing facebook instructions

---

CHANGELOG.rst
docs/docker_walkthrough.rst
docs/index.rst
docs/quickstart.rst

- see https://github.com/RasaHQ/rasa_core/issues/1239

add docker tutorial for core & nlu #1239

---

rasa_core/evaluate.py

- Fix error when logging failed end-2-end stories during e2e evaluation

fix bug when logging failed e2e stories

---

.travis.yml
docs-requirements.txt

increment docs theme version

---

CHANGELOG.rst
docs/_static/spec/server.yml
rasa_core/server.py

- there was an issue with the name parameter not getting extracted properly when an executed action is submitted to the core server - this PR fixes this
- fixes #1320

fix execute endpoint accepting name parameter

---

CHANGELOG.rst
rasa_core/channels/slack.py

Instantiate SlackBot with slack_channel kwarg

---

rasa_core/training/interactive.py

Naive fix for issue #1321, please check if this is correct way, how to handle this.

Fix #1321, pass 'forms' as a list

---

.travis.yml
CHANGELOG.rst
docs-requirements.txt
rasa_core/channels/slack.py
rasa_core/policies/keras_policy.py
rasa_core/training/interactive.py

Prepare minor release 0.12.1

---

.travis.yml
README.md
rasa_core/agent.py
rasa_core/channels/console.py
rasa_core/channels/facebook.py
rasa_core/domain.py
rasa_core/tracker_store.py
rasa_core/training/interactive.py
rasa_core/utils.py
requirements.txt
setup.cfg
setup.py
tests/test_policies.py
tests/utilities.py

- removed python 2 compatible code
- reduced build to run on py3.x (travis)
- won't build a python 2 wheel no more
- removed `six` dependency

remove python 2 support

---

data/test_stories/stories_unused_checkpoints.md
rasa_core/training/generator.py
rasa_core/training/structures.py
tests/test_dsl.py

fix ignoring story steps with unused end checkpoints add tests

---

tests/test_interactive.py

- PR for merge as discussed in #1353 (I've deleted source branch and now cannot reopen the original PR)

test domain save from interactive training - merge

---

CHANGELOG.rst
examples/restaurantbot/policy.py
requirements.txt
setup.py

- remove keras requirment since we moved to tf.keras

remove keras requirment since we moved to tf.keras

---

docs/slotfilling.rst

- add section that form actions should be added under forms: section in the domain file

add section that form actions should be added under forms: section in the domain file

---

docs/policies.rst
rasa_core/policies/embedding_policy.py
rasa_core/policies/tf_utils.py

- add our paper https://arxiv.org/abs/1811.11707 to class description and docs

add our paper to class description and docs

---

.travis.yml
CHANGELOG.rst
dev-requirements.txt
rasa_core/agent.py
rasa_core/policies/tf_utils.py
rasa_core/tracker_store.py
setup.cfg
setup.py
tests/test_domain.py
tests/test_utils.py

- fixes https://github.com/RasaHQ/rasa_core/issues/1445
- ~[ ] added some tests for the functionality~
- ~[ ] updated the documentation~

Pycodestyle

---

CHANGELOG.rst
requirements.txt
setup.py

- fixes https://github.com/RasaHQ/rasa_core/issues/1479
- ~[ ] added some tests for the functionality~
- ~[ ] updated the documentation~

re-add python-engineio dependency

---

docs/tracker_stores.rst

- Documentation update based on #1502

Add note on advanced configuration for mongodb

---

.travis.yml
CHANGELOG.rst

- To solve [this issue](https://github.com/RasaHQ/rasa_core/issues/1427)
- Add an extra stage to the travis script which clones the [stack starter pack](https://github.com/RasaHQ/starter-pack-rasa-stack) and tests it upon successful core build

Create downstream travis jobs for the starter packs

---

requirements.txt
setup.py

- re-introduce missing python-engineio (3.0) dependency in requirements.txt and setup.py 

fix missing enginio dependency

---

examples/formbot/README.md
examples/formbot/data/nlu_data.md
examples/formbot/data/stories.md
examples/formbot/domain.yml

I want to reuse this example for the forms tutorial. Without changing too much on the code side, proposing a few improvements on the NLU side and additional intent to make the conversation a bit more natural.
- A few more examples to NLU training data and added greet intent
- Updated stories and domain accordingly
- Added a short readme

Formbot: small updates on training data

---

docs/fallbacks.rst
docs/slotfilling.rst

Re: https://github.com/RasaHQ/roadmap/issues/329
- added the configuration example for fallback action
- mentioned that FormPolicy has to be included into the config.yml
- added an example for action_deactivate_form

added configuration for fallback and forms

---

docs/slotfilling.rst

- substitute text code blocks in slotfilling docs with auto include from code base
- fixes #1524

fix slot filling docs

---

CHANGELOG.rst
docs/interactive_learning.rst

- Added a note to inform users they can pass a pre-trained model into interactive learning, fixes #1573 

Update docs to include --core flag

---

CHANGELOG.rst
rasa_core/policies/fallback.py
rasa_core/policies/two_stage_fallback.py
rasa_core/trackers.py
tests/test_policies.py

- change condition to check for latest action to be listen
- fixes #1533 

fix fallback

---

rasa_core/interpreter.py

- Refine codes to clarify some if/else logic.

Refine some if/else logic

---

CHANGELOG.rst
docs/connectors.rst

- update custom channel docs to use credentials.yaml
~- [ ] added some tests for the functionality~

update custom channel docs to use credentials.yml

---

rasa_core/agent.py
rasa_core/policies/keras_policy.py

- adds last changes from @Ghostvv missed before merging #1635 

update #1635 merge

---

CHANGELOG.rst
rasa_core/processor.py
tests/test_processor.py

Pass message_id with processor

---

examples/nlg_server/nlg_server.py

- make nlg server example async
- ~[ ] added some tests for the functionality~
- ~[ ] updated the documentation~
- ~[ ] updated the changelog~

Async nlg server example

---

README.md

- Update all docs links from core.rasa.com to new location, rasa.com/docs/core/
- Add image of Sara the Rasa mascot
- Formatting fixes - move quicklinks further down

Update docs links to new docs url, add Sara the Rasa mascot, formatting updates

---

rasa_core/training/interactive.py

- saves story when fork is created
- fixes #1606 

fork saving fix

---

rasa_core/utils.py

Set default log file encoding to utf-8
- ...

Set default log file encoding to utf-8 for #1776

---

CHANGELOG.rst
docs/changelog.rst

- I followed the example of someone else who was also confused about where to put things in the changelog, and am moving both of our changelog updates to the true one 🙈

move changes from changelog to CHANGELOG

---

rasa_core/training/interactive.py

- properly encode table in interactive learning before dumping it to file

properly encode table before printing it

---

README.md

- added a note to the readme about the code move.

Merge note in readme

---

examples/formbot/Makefile
rasa_core/evaluate.py
rasa_core/policies/form_policy.py

fix evaluation with forms

---

CHANGELOG.rst
rasa_core/policies/mapping_policy.py
tests/test_domain.py

- fix mapping policy bug
- fix https://github.com/RasaHQ/rasa/issues/3328

fix bug and outdated changelog

---

docs/core/old_core_changelog.rst
rasa/core/policies/mapping_policy.py
tests/core/test_domain.py

Merge mapping fix

---

rasa_core/test.py

Don't know where we lost it but fix form evaluation again 
https://github.com/RasaHQ/rasa/pull/3140/files

port fix of form evaluation to 0.14.x

---

docs/core/old_core_changelog.rst

Checked and the test script is correct on master, as is the formpolicy -- this should be the only thing needed to add to master

add changelog for latest release
